#!/bin/bash

############################################################################################################
# The directory where this script is located and executed is referred to as the 'top' directory.
# Run this bash script in the top directory as
# $ ./VASP-setup.sh $1
# where $1 is an integer equal to the number of POSCAR files generated by phonopy/phono3py.
#
# All POSCAR-#### files should be in the top directory where this script is run.
# The CHG CHGCAR and WAVECAR files from the undisplaced POSCAR file can be kept in the top directory.
# Since the displaced POSCAR files may have different symmetry the CHG,CHGCAR and WAVECAR may not 
# load properly. In the top directory a directory called 'base' (/top/base/) should contain all VASP 
# input files which are common to each VASP calculation, e.g., INCAR, POTCAR, KPOINTS, and a 
# submission script if relevant. As originally set up, a bash script called runVASP.sh should be 
# present in the /top/base/ directory, which submits the job to a computer where the VASP program is
# run.
# 
# This script creates and submits a VASP calculation for each POSCAR file generated by phonopy/phono3py 
# in the following order.
#
# 1. A directory is made in the top directory called ##### corresponding to POSCAR-#####, 
#    (firstly will be 00001 for POSCAR-00001)
# 2. All files from the directory 'base' are copied into the directory '00001'
# 3. The file 'POSCAR-00001' is copied from the top directory to '00001'
# 4. Soft links are set up to read the CHG, CHGCAR, and WAVECAR files in the top directory, in order to 
#    avoid making many copies of these large files.
# 5. A submission script is ran using the command 'sbatch runVASP.sh' where runVASP.sh submits a job to a 
#    computer and runs the VASP program.
# 6. Repeat steps 1-5 for POSCAR-00002, and so on up to POSCAR-##### specified by $1.
#############################################################################################################

echo "making $1 directories"
for i in $(seq 1 $1) ; do
length=$(echo ${#i})
if [ $length -eq 1 ]
then
    prefix="0000"
    prefix="$prefix$i"
    mkdir $prefix
    cp base/* $prefix
    cat POSCAR-$prefix > $prefix/POSCAR
    cd $prefix
    ln -s ../WAVECAR WAVECAR
    ln -s ../CHG CHG
    ln -s ../CHGCAR CHGCAR
    sbatch runVASP.sh
    cd ../
elif [ $length -eq 2 ]
then
    prefix="000"
    prefix="$prefix$i"
    mkdir $prefix
    cp base/* $prefix
    cat POSCAR-$prefix > $prefix/POSCAR
    cd $prefix
    ln -s ../WAVECAR WAVECAR
    ln -s ../CHG CHG
    ln -s ../CHGCAR CHGCAR
    sbatch runVASP.sh
    cd ../
elif [ $length -eq 3 ]
then
    prefix="00"
    prefix="$prefix$i"
    mkdir $prefix
    cp base/* $prefix
    cat POSCAR-$prefix > $prefix/POSCAR
    cd $prefix
    ln -s ../WAVECAR WAVECAR
    ln -s ../CHG CHG
    ln -s ../CHGCAR CHGCAR
    sbatch runVASP.sh
    cd ../
else
    echo "good luck with all that"
fi
done

echo "$1 directories created and $1 jobs submitted"
